services:
  rdmodels:
    image: robotics-deployment:models-dev
    privileged: true
    container_name: rdmodels
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CARGO_REGISTRIES_RD_TOKEN=${CARGO_REGISTRIES_RD_TOKEN}
    working_dir: /opt/rdmodels
    volumes:
      - ~/repos/roboticsdeployment/models:/opt/rdmodels
      - ~/.gitconfig:/home/dev/.gitconfig
      - ~/.ssh:/home/dev/.ssh
      - ~/.config/gcloud:/home/dev/.config/gcloud
      - ~/.config/lazygit:/home/dev/.config/lazygit
      - ~/.config/nvim:/home/dev/.config/nvim
      - ~/.config/github-copilot:/home/dev/.config/github-copilot
      - ~/.local/state/nvim:/home/dev/.local/state/nvim
      - ~/.local/share/nvim:/home/dev/.local/share/nvim
      - ~/.cache/nvim:/home/dev/.cache/nvim
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["sleep", "infinity"]
