services:
  rdprovisioner:
    image: robotics-deployment:provisioner-dev
    privileged: true
    container_name: rdprovisioner 
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    working_dir: /opt/rdprovisioner
    volumes:
      - ~/repos/roboticsdeployment/provisioner:/opt/rdprovisioner
      - ~/.aws:/home/dev/.aws
      - ~/.gitconfig:/home/dev/.gitconfig
      - ~/.cargo/config.toml:/opt/cargo/config.toml
      - ~/.cargo/credentials.toml:/opt/cargo/credentials.toml
      - ~/.cargo/registry:/opt/cargo/registry
      - ~/.ssh:/home/dev/.ssh
      - ~/.config/gcloud:/home/dev/.config/gcloud
      - ~/.config/lazygit:/home/dev/.config/lazygit
      - ~/.config/nvim:/home/dev/.config/nvim
      - ~/.config/github-copilot:/home/dev/.config/github-copilot
      - ~/.local/state/nvim:/home/dev/.local/state/nvim
      - ~/.local/share/nvim:/home/dev/.local/share/nvim
      - ~/.cache/nvim:/home/dev/.cache/nvim
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["sleep", "infinity"]

